name: build-test-windows-on-push

on: [push, pull_request]

jobs:
  build-cmake-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Add MSVC to PATH
      - uses: ilammy/msvc-dev-cmd@v1

      # - name: Install CMake and Ninja
      #   uses: lukka/get-cmake@v3.27.6
      
      # - name: Setup anew (or from cache) vcpkg (and does not build any package)
      # - uses: lukka/run-vcpkg@v11

      # - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      #   uses: lukka/run-cmake@v10

      - name: Configure C/C++ with CMake
        run: |
          cmake -D CMAKE_BUILD_TYPE=Debug -D BUILD_TESTING=ON -D SWIG_PYTHON=OFF -S . -B build -G Ninja -D CMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake -D MOD_AVFORMAT=OFF -D MOD_DECKLINK=OFF -D MOD_FREI0R=OFF -D MOD_GDK=OFF -D MOD_JACKRACK=OFF -D USE_LV2=OFF -D USE_VST2=OFF -D MOD_KDENLIVE=OFF -D MOD_NDI=OFF -D MOD_NORMALIZE=OFF -D MOD_OLDFILM=OFF -D MOD_OPENCV=OFF -D MOD_MOVIT=OFF -D MOD_PLUS=OFF -D MOD_PLUSGPL=OFF -D MOD_QT6=OFF -D MOD_RESAMPLE=OFF -D MOD_RTAUDIO=OFF -D MOD_RUBBERBAND=OFF -D MOD_SDL2=OFF -D MOD_DOX=OFF -D MOD_VIDSTAB=OFF -D MOD_VORBIS=OFF -D MOD_XINE=OFF -D MOD_XML=OFF

      - name: Build with Ninja
        run: |
          cmake --build build
          cmake --install build
      - name: Run tests
        run: cd build && ctest --output-on-failure
